export const PATTERN_CONFIG = {
  LOOKBACK: 50,
  MIN_MOVE_PERCENT: 0.75,

  DOUBLE_BOTTOM: {
    MAX_DIFFERENCE_PERCENT: 3,
    MIN_NECKLINE_PERCENT: 1.5,
    MIN_LEG_BALANCE: 0.3,
  },

  DOUBLE_TOP: {
    MAX_DIFFERENCE_PERCENT: 3,
    MIN_NECKLINE_PERCENT: 1.5,
    MIN_LEG_BALANCE: 0.3,
  },

  HEAD_AND_SHOULDERS: {
    MAX_SHOULDER_DIFFERENCE_PERCENT: 4,
    MAX_NECKLINE_DIFFERENCE_PERCENT: 4,
    MIN_HEAD_HEIGHT_PERCENT: 1.5,
  },
} as const;